####################################
## DEPLOYMENT_REPO-VARIABLES.YAML ##
####################################
deployment:
  viya4:
    # Get this information from your POC Viya Order - https://apiportal.sas.com/get-started
    cadencename: 'stable'
    cadenceversion: '2021.1.5'
    ordernumber: '09XXXX'
    orderapikey: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    orderapisecret: 'XXXXXXXXXXXXXXXX'
    iacazure: 
      tag: '4.0.0'
    viya4deployment:
      versiontag: '4.2.0'
